# creates the docker compose
# Modified to connect to existing Ollama instance on host machine

# build individual services
services:
  # setup discord bot container
  discord:
    build: ./                     # find docker file in designated path
    container_name: discord
    restart: always               # rebuild container always
    image: kevinthedang/discord-ollama:0.8.7
    environment:
      CLIENT_TOKEN: ${CLIENT_TOKEN}
      OLLAMA_IP: ${OLLAMA_IP}     # Use host.docker.internal or host IP
      OLLAMA_PORT: ${OLLAMA_PORT}
      MODEL: ${MODEL}
    # Use host networking to access Ollama on localhost
    # Comment out network_mode and uncomment 'networks' if you prefer bridge networking
    network_mode: host
    # networks:
    #   - discord-net
    volumes:
      - discord:/src/app          # docker will not make this for you, make it yourself

# Optional: Use bridge network instead of host networking
# networks:
#   discord-net:
#     driver: bridge

volumes:
  discord:
