# creates the docker compose
# Modified to connect to OpenWebUI's Ollama via Docker networking

# build individual services
services:
  # setup discord bot container
  discord:
    build: ./                     # find docker file in designated path
    container_name: discord
    restart: always               # rebuild container always
    image: kevinthedang/discord-ollama:0.8.7
    environment:
      CLIENT_TOKEN: ${CLIENT_TOKEN}
      OLLAMA_IP: ${OLLAMA_IP}     # Use container name: open-webui
      OLLAMA_PORT: ${OLLAMA_PORT}
      OLLAMA_API_KEY: ${OLLAMA_API_KEY:-}  # Optional API key for Ollama auth
      MODEL: ${MODEL}
    # Connect to OpenWebUI's Docker network
    networks:
      - default
    volumes:
      - discord:/src/app          # docker will not make this for you, make it yourself

# Use the default bridge network
# OpenWebUI should be on this network too
networks:
  default:
    name: bridge
    external: true

volumes:
  discord:
